[package]
name = "neko"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.5.1"
chumsky = "0.10.1"
clap = { version = "4.5.38", features = ["derive"] }
petgraph = "0.8.1"
rand = "0.9.1"
thiserror = "2.0.12"
